#!/usr/bin/env bash
#
# prompt-magic sync — generate one espanso match file from prompts/*.md
# and install it into espanso's match directory.
#
#   scripts/sync.sh            generate + install into espanso's match dir
#   scripts/sync.sh --stdout   print the generated YAML to stdout (no install)
#
# Each prompts/<name>.md becomes one match: trigger ":<name>", label from the
# frontmatter `description:`, and replace = the prompt body.
set -euo pipefail

# Resolve repo root from the script's own location so it runs from any cwd.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
PROMPTS_DIR="$REPO_ROOT/prompts"

HEADER="# GENERATED by prompt-magic sync.sh — do not edit.
# Source of truth: prompts/*.md. Regenerate with scripts/sync.sh."

# Emit the full match file to stdout.
generate() {
  printf '%s\n' "$HEADER"
  printf 'matches:\n'
  local f name desc label body
  for f in "$PROMPTS_DIR"/*.md; do
    [ -e "$f" ] || continue
    name="$(basename "$f" .md)"

    # description: the first `description:` line inside the YAML frontmatter.
    desc="$(awk '
      NR==1 && /^---[[:space:]]*$/ { infm=1; next }
      infm && /^---[[:space:]]*$/ { exit }
      infm && /^[[:space:]]*description:[[:space:]]*/ {
        sub(/^[[:space:]]*description:[[:space:]]*/, ""); print; exit
      }' "$f")"

    # body: every line after the closing frontmatter delimiter. Only the first
    # two `---` lines are treated as delimiters, so a `---` rule inside the body
    # survives.
    body="$(awk '
      seen<2 && /^---[[:space:]]*$/ { seen++; next }
      seen>=2 { print }' "$f")"

    # Single-quoted YAML scalar for the label; double any embedded single quote.
    label="${desc//\'/\'\'}"

    printf '  - trigger: ":%s"\n' "$name"
    printf "    label: '%s'\n" "$label"
    printf '    replace: |-\n'
    # Literal block scalar: strip leading/trailing blank lines, indent the rest
    # by 6 spaces. No escaping needed — quotes, colons and backticks pass through.
    printf '%s\n' "$body" | awk '
      { lines[NR] = $0 }
      END {
        start = 1;   while (start <= NR && lines[start] ~ /^[[:space:]]*$/) start++
        end   = NR;  while (end   >= start && lines[end] ~ /^[[:space:]]*$/) end--
        for (i = start; i <= end; i++) printf "      %s\n", lines[i]
      }'
  done
}

# Locate espanso's match directory (config dir + /match).
resolve_match_dir() {
  local cfg
  if cfg="$(espanso path config 2>/dev/null)" && [ -n "$cfg" ]; then
    printf '%s/match' "$cfg"; return 0
  fi
  cfg="$(espanso path 2>/dev/null | awk -F': ' '/^Config/{print $2; exit}')"
  if [ -n "$cfg" ]; then printf '%s/match' "$cfg"; return 0; fi
  return 1
}

if [ "${1:-}" = "--stdout" ]; then
  generate
  exit 0
fi

if ! command -v espanso >/dev/null 2>&1; then
  echo "error: espanso not found on PATH. Use --stdout to preview, or install espanso first." >&2
  exit 1
fi

match_dir="$(resolve_match_dir)" || {
  echo "error: could not resolve espanso match directory from 'espanso path'." >&2
  exit 1
}
mkdir -p "$match_dir"
out="$match_dir/prompt-magic.yml"
generate > "$out"
echo "Installed $(grep -c '^  - trigger:' "$out") prompts -> $out"
